---
title: "Data"
format:
  html:
    code-fold: true
    code-tools: true
---

# Importing Data Set

Data source: [TUIK](https://data.tuik.gov.tr/)

```{r}
#| code-fold: true
#| output: false
library(readxl)
library(tidyverse)
library(rvest)
library(stringr)
library(knitr)
data1 <- read_excel("C:/Users/kubil/Desktop/veri seti.xls")
save(data1, file = "semicolon.RData")
```

Download the data set : [semicolon.RData](https://github.com/emu-hacettepe-analytics/emu430-fall2023-team-semicolon/raw/master/semicolon.RData)

# Data Explanation

Our dataset classifies suicides between the years 2002-2022 based on **reasons**, **gender**, and **age groups**.

## Why this data set?

We choose this data set based on this reasons:

-   There are so many observations in this data set

-   Data has been divided into multiple categories

-   Source of the data set is reliable **(TUİK)**

-   Data set didn't need any preprocessing

## What are the categories of this data set?

The reasons for suicides in this dataset are categorized into eight groups:

-   Illness

-   Family incompatibility

-   Economic problems

-   Business failure

-   Emotional relationships and not marrying the person wanted

-   Educational failure

-   Other

-   Unknown.

## What are the age groups of this data set?

Age groups are classified as :

-   \<15

-   15-19

-   20-24

-   25-29

-   30-34

-   35-39

-   40-44

-   45-49

-   50-54

-   55-59

-   60-64

-   65-69

-   70-74

-   +75.

## What is our aim?

By leveraging this dataset, we aim to answer the following questions:

-   Suicide rates by gender regardless of age and reason

-   Suicide rates by age regardless of gender and reason

-   Suicide rates by reasons regardless of age and gender

-   The most observed reason for suicides for females/males

-   The most observed reason for suicides for teenagers

By obtaining answers to these questions, we can understand how to approach preventing suicides for different age groups and genders.
